### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by p5150j** [CodeForFoco/bike-coop#1]
things like 
- how to fork
- gitflow

**Comment by JordanMajd** [comment]
Setting up wordpress resources and using the theme.

**Comment by p5150j** [comment]
Ill put this here till its in the readme
https://help.github.com/articles/fork-a-repo/

**Comment by p5150j** [comment]
and this  https://guides.github.com/introduction/flow/

**Comment by abettermap** [comment]
Should also maybe go into README...

Show people how to set up a WP dev environment. [MAMP](https://www.mamp.info/en/) is a good option, and I've had good luck with a [WP-specific Vagrant option](https://github.com/bradp/vv) which takes a little overhead for setup but works like a champ.

**Comment by abettermap** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sFKXUBBZ&#x2F;22-setup-instructions-on-setting-up-project-and-local-wp-instance"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Setup -- Instructions on setting up project and local WP Instance</a>

**Comment by idcrook** [comment]
I was able to use C9 and get the site up. I made a PR #18 that updated the starting instructions.  I think this issue can be closed.

**Comment by JordanMajd** [comment]
👍
