### ISSUE TITLE
create header and nav links html css

### ISSUE THREAD

**Issue by p5150j** [CodeForFoco/bike-coop#11]
here part of the comp
<img width="1085" alt="screen shot 2016-08-18 at 6 29 33 pm" src="https://cloud.githubusercontent.com/assets/444888/17795021/d1021990-6571-11e6-81cd-22ab8606d0fc.png">

**Comment by abettermap** [comment]
Trello card: https://trello.com/c/IYMKL3mo

**Comment by abettermap** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IYMKL3mo&#x2F;5-theme-header-nav-links"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Theme -- Header&#x2F;Nav&#x2F;Links</a>
