### ISSUE TITLE
image slider js please

### ISSUE THREAD

**Issue by p5150j** [CodeForFoco/bike-coop#12]
here is a comp for it..
<img width="750" alt="screen shot 2016-08-18 at 6 31 46 pm" src="https://cloud.githubusercontent.com/assets/444888/17795038/11441f08-6572-11e6-853c-033c5ac6b0ac.png">

**Comment by abettermap** [comment]
Trello: https://trello.com/c/HUeqM2HD

**Comment by abettermap** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;HUeqM2HD&#x2F;2-add-foundation-orbit-image-slider"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add Foundation Orbit (image slider)</a>
