### ISSUE TITLE
content (text and images) section html css

### ISSUE THREAD

**Issue by p5150j** [CodeForFoco/bike-coop#13]
see comp..
<img width="889" alt="screen shot 2016-08-18 at 6 45 39 pm" src="https://cloud.githubusercontent.com/assets/444888/17795257/1175a120-6574-11e6-9bb8-046c7268619b.png">

**Comment by abettermap** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;keoiyGdE&#x2F;31-theme-page-templates"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Theme -- Page Templates</a>
