### ISSUE TITLE
Create Volunteer Application Form

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/bike-coop#9]
Must be mobile friendly and include all the fields from the [original page](http://fcbikecoop.org/volunteer_db/volunteer_form.php)

**Comment by abettermap** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;l1oCpTdS&#x2F;29-forms-volunteer-form"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Forms -- Volunteer Form</a>
